power = {'BUSES': {'Area': 16.0146,
           'Bus/Area': 16.0146,
           'Bus/Gate Leakage': 0.0429624,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.448008,
           'Bus/Subthreshold Leakage with power gating': 0.168003,
           'Gate Leakage': 0.0429624,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.448008,
           'Subthreshold Leakage with power gating': 0.168003},
 'Core': [{'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00246753,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.204627,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0198228,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.312754,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.376693,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 5.59509,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 1874.72,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 1880.7,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.207089,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.271848,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202645.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.704771,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0944419,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 1.08147,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.795729,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 1.78624,
           'Execution Unit/Register Files/Runtime Dynamic': 0.890171,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.191995,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 5.31291,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 1887.69,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00228472,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00228472,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00197525,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000756584,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000852986,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00739768,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0224326,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 23.6834,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 5.17261,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.189451,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.193891,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4058.27,
           'Instruction Fetch Unit/Runtime Dynamic': 24.0965,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.55594,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.11607,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0750193,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0750193,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 5.32609,
           'Load Store Unit/Runtime Dynamic': 1.56107,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.184985,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.36997,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0656517,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.065733,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.225773,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0146645,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.54771,
           'Memory Management Unit/Runtime Dynamic': 0.0804105,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209268.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.307037,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.132585,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 21.6947,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 22.1344,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 1935.56,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00246753,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.204627,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0198228,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.312754,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.313826,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 4.66131,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 1577.17,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 1582.14,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.172051,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.245631,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202644.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.704771,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0786793,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.951656,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.662927,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 1.65643,
           'Execution Unit/Register Files/Runtime Dynamic': 0.741606,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.169637,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 4.50762,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 1588.15,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00185869,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00185869,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00160703,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000615606,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000710651,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00603506,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0182456,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 19.7308,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 4.30934,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.189478,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.161532,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4056.94,
           'Instruction Fetch Unit/Runtime Dynamic': 20.1061,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.19418,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.942996,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0633157,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0633158,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 4.68817,
           'Load Store Unit/Runtime Dynamic': 1.31858,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.156126,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.312252,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0554095,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0554871,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.188093,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0146672,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.38199,
           'Memory Management Unit/Runtime Dynamic': 0.0701673,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209266.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.307037,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.11076,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 18.0745,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 18.4923,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 1628.14,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00246753,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.204627,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0198228,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.312754,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.31902,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 4.73849,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 1601.74,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 1606.8,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.174944,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.247795,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202644.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.704771,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0799823,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.962375,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.673903,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 1.66715,
           'Execution Unit/Register Files/Runtime Dynamic': 0.753885,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.171483,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 4.57408,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 1612.89,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00189381,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00189381,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00163735,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000627193,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000722413,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00614739,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0185922,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 20.0574,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 4.38068,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.189451,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.164206,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4057.05,
           'Instruction Fetch Unit/Runtime Dynamic': 20.4358,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.2241,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.95765,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0642836,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0642836,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 4.74093,
           'Load Store Unit/Runtime Dynamic': 1.33897,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.158512,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.317025,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0562566,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.056335,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.191207,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0146651,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.3957,
           'Memory Management Unit/Runtime Dynamic': 0.0710131,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209266.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.307037,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.112564,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 18.3737,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 18.7933,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 1653.53,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00246753,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.204627,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0198228,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.312754,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.413315,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 6.13906,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 2048.1,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 2054.66,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.22752,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.287127,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202645.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.704771,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.103624,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 1.15716,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.87309,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 1.86194,
           'Execution Unit/Register Files/Runtime Dynamic': 0.976713,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.205031,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 5.78221,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 2062.22,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00253234,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00253234,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00218912,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000838392,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000935956,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00818975,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.024871,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 25.9859,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 5.6755,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.189573,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.212741,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4059.05,
           'Instruction Fetch Unit/Runtime Dynamic': 26.4213,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.76653,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.21703,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0818323,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0818323,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 5.69743,
           'Load Store Unit/Runtime Dynamic': 1.70244,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.201784,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.403569,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.071614,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0716929,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.247723,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0146751,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.6442,
           'Memory Management Unit/Runtime Dynamic': 0.086381,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209270.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.307037,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.145299,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 23.8037,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 24.256,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 2114.69,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.020399422740592105,
          'Runtime Dynamic': 0.020399422740592105,
          'Subthreshold Leakage': 4.252,
          'Subthreshold Leakage with power gating': 4.252},
 'L2': [{'Area': 22.2273,
         'Gate Leakage': 0.0518439,
         'Peak Dynamic': 0.0395948,
         'Runtime Dynamic': 0.022369,
         'Subthreshold Leakage': 2.01996,
         'Subthreshold Leakage with power gating': 0.908099}],
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.00136138,
         'Runtime Dynamic': 0.000440559,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 7207.04,
               'Gate Leakage': 22.6747,
               'Peak Dynamic': 837070.0,
               'Peak Power': 837408.0,
               'Runtime Dynamic': 7331.94,
               'Subthreshold Leakage': 314.937,
               'Subthreshold Leakage with power gating': 135.294,
               'Total Cores/Area': 7106.89,
               'Total Cores/Gate Leakage': 22.5315,
               'Total Cores/Peak Dynamic': 837070.0,
               'Total Cores/Runtime Dynamic': 7331.92,
               'Total Cores/Subthreshold Leakage': 305.668,
               'Total Cores/Subthreshold Leakage with power gating': 130.41,
               'Total L2s/Area': 22.2273,
               'Total L2s/Gate Leakage': 0.0518439,
               'Total L2s/Peak Dynamic': 0.0395948,
               'Total L2s/Runtime Dynamic': 0.022369,
               'Total L2s/Subthreshold Leakage': 2.01996,
               'Total L2s/Subthreshold Leakage with power gating': 0.908099,
               'Total L3s/Area': 61.9075,
               'Total L3s/Gate Leakage': 0.0484137,
               'Total L3s/Peak Dynamic': 0.00136138,
               'Total L3s/Runtime Dynamic': 0.000440559,
               'Total L3s/Subthreshold Leakage': 6.80085,
               'Total L3s/Subthreshold Leakage with power gating': 3.32364,
               'Total Leakage': 337.611,
               'Total NoCs/Area': 16.0146,
               'Total NoCs/Gate Leakage': 0.0429624,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.448008,
               'Total NoCs/Subthreshold Leakage with power gating': 0.168003}}