power = {'BUSES': {'Area': 16.0146,
           'Bus/Area': 16.0146,
           'Bus/Gate Leakage': 0.0429624,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.448008,
           'Bus/Subthreshold Leakage with power gating': 0.168003,
           'Gate Leakage': 0.0429624,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.448008,
           'Subthreshold Leakage with power gating': 0.168003},
 'Core': [{'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00251004,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.20466,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0201695,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.312906,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.439316,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 6.52524,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 2469.21,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 2476.17,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.24195,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.341724,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202645.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.717094,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.110142,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 1.21604,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.928014,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 1.93313,
           'Execution Unit/Register Files/Runtime Dynamic': 1.03816,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.21527,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 7.46052,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 2485.53,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00228228,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00228228,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.0019738,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.0007564,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000994846,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0075332,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0223847,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 27.6206,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 6.03253,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.165136,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.226124,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4059.6,
           'Instruction Fetch Unit/Runtime Dynamic': 28.0418,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 4.30003,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.51313,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0990925,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0990927,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 6.63821,
           'Load Store Unit/Runtime Dynamic': 2.10093,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.244345,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.488691,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0867189,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.088734,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.263307,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0127831,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.84861,
           'Memory Management Unit/Runtime Dynamic': 0.10153,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209272.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.312391,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.154356,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 25.3101,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 25.7769,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 2541.55,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00251004,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.20466,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0201695,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.312906,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.460902,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 6.84587,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 2591.79,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 2599.1,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.253986,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.353722,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202645.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.717094,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.115554,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 1.26063,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.973613,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 1.97773,
           'Execution Unit/Register Files/Runtime Dynamic': 1.08917,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.22295,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 7.82905,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 2608.89,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00239896,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00239896,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00207453,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000794899,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00104368,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00791612,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0235356,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 28.9777,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 6.32894,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.165259,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.237235,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4060.06,
           'Instruction Fetch Unit/Runtime Dynamic': 29.4117,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 4.44877,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.57711,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.103905,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.103905,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 6.90049,
           'Load Store Unit/Runtime Dynamic': 2.19345,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.256211,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.512423,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0909301,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0927974,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.276245,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0127933,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.91419,
           'Memory Management Unit/Runtime Dynamic': 0.105604,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209272.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.312391,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.16185,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 26.5538,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 27.028,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 2667.63,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00251004,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.20466,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0201695,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.312906,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.437153,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 6.49313,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 2456.89,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 2463.82,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.240735,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.340517,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202645.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.717094,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.109599,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 1.21154,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.923447,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 1.92863,
           'Execution Unit/Register Files/Runtime Dynamic': 1.03305,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.214495,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 7.42342,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 2473.14,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00227097,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00227097,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00196411,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.00075274,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000989947,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00749599,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0222703,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 27.4847,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 6.00285,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.165314,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.225011,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4059.56,
           'Instruction Fetch Unit/Runtime Dynamic': 27.9048,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 4.28468,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.49973,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.098596,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0985961,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 6.61115,
           'Load Store Unit/Runtime Dynamic': 2.08458,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.243121,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.486242,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0862844,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0881147,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.262011,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0127975,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.84188,
           'Memory Management Unit/Runtime Dynamic': 0.100926,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209271.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.312391,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.153606,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 25.1856,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 25.6516,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 2528.88,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.00251004,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.20466,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0201695,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.312906,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.31634,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 4.69865,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 1770.75,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 1775.76,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.173408,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.273355,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202644.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.717094,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0793104,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.962098,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.668238,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 1.67919,
           'Execution Unit/Register Files/Runtime Dynamic': 0.747548,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.171534,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 5.36052,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 1782.66,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00161526,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00161526,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00139728,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000535652,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000716296,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0053441,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0158305,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 19.8888,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 4.34386,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.165218,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.162826,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4056.99,
           'Instruction Fetch Unit/Runtime Dynamic': 20.2381,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.45065,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.09312,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.071613,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0716132,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 5.14043,
           'Load Store Unit/Runtime Dynamic': 1.51792,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.176585,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.353172,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0626708,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0639247,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.1896,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0127901,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.47428,
           'Memory Management Unit/Runtime Dynamic': 0.0767281,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209267.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.312391,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.111665,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 18.2249,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 18.649,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 1823.14,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.01960207071269304,
          'Runtime Dynamic': 0.01960207071269304,
          'Subthreshold Leakage': 4.252,
          'Subthreshold Leakage with power gating': 4.252},
 'L2': [{'Area': 22.2273,
         'Gate Leakage': 0.0518439,
         'Peak Dynamic': 0.838313,
         'Runtime Dynamic': 0.472809,
         'Subthreshold Leakage': 2.01996,
         'Subthreshold Leakage with power gating': 0.908099}],
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 0.00150297,
         'Runtime Dynamic': 0.000449635,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 7207.04,
               'Gate Leakage': 22.6747,
               'Peak Dynamic': 837083.0,
               'Peak Power': 837420.0,
               'Runtime Dynamic': 9561.67,
               'Subthreshold Leakage': 314.937,
               'Subthreshold Leakage with power gating': 135.294,
               'Total Cores/Area': 7106.89,
               'Total Cores/Gate Leakage': 22.5315,
               'Total Cores/Peak Dynamic': 837082.0,
               'Total Cores/Runtime Dynamic': 9561.2,
               'Total Cores/Subthreshold Leakage': 305.668,
               'Total Cores/Subthreshold Leakage with power gating': 130.41,
               'Total L2s/Area': 22.2273,
               'Total L2s/Gate Leakage': 0.0518439,
               'Total L2s/Peak Dynamic': 0.838313,
               'Total L2s/Runtime Dynamic': 0.472809,
               'Total L2s/Subthreshold Leakage': 2.01996,
               'Total L2s/Subthreshold Leakage with power gating': 0.908099,
               'Total L3s/Area': 61.9075,
               'Total L3s/Gate Leakage': 0.0484137,
               'Total L3s/Peak Dynamic': 0.00150297,
               'Total L3s/Runtime Dynamic': 0.000449635,
               'Total L3s/Subthreshold Leakage': 6.80085,
               'Total L3s/Subthreshold Leakage with power gating': 3.32364,
               'Total Leakage': 337.611,
               'Total NoCs/Area': 16.0146,
               'Total NoCs/Gate Leakage': 0.0429624,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.448008,
               'Total NoCs/Subthreshold Leakage with power gating': 0.168003}}