power = {'BUSES': {'Area': 16.0146,
           'Bus/Area': 16.0146,
           'Bus/Gate Leakage': 0.0429624,
           'Bus/Peak Dynamic': 0.0,
           'Bus/Runtime Dynamic': 0.0,
           'Bus/Subthreshold Leakage': 0.448008,
           'Bus/Subthreshold Leakage with power gating': 0.168003,
           'Gate Leakage': 0.0429624,
           'Peak Dynamic': 0.0,
           'Runtime Dynamic': 0.0,
           'Subthreshold Leakage': 0.448008,
           'Subthreshold Leakage with power gating': 0.168003},
 'Core': [{'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0067328,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.207977,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0362453,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.319978,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.336031,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 4.99112,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 2065.98,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 2071.31,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.182016,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.31062,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202646.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 1.28865,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.084248,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 1.53173,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.709834,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 2.82038,
           'Execution Unit/Register Files/Runtime Dynamic': 0.794082,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.279453,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 6.59351,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 2079.54,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00136915,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00136915,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00118321,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000452943,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.000760958,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00468248,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0134603,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 21.1268,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 4.61425,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.00406136,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.172961,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4057.41,
           'Instruction Fetch Unit/Runtime Dynamic': 21.322,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 3.31053,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.996143,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0670798,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0670797,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 4.89334,
           'Load Store Unit/Runtime Dynamic': 1.39404,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.165407,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.330814,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0587036,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0588268,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.201402,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.000314425,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.43648,
           'Memory Management Unit/Runtime Dynamic': 0.0591416,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209268.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.561376,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.119973,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 19.3644,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 20.0458,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 2122.36,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0067328,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.207977,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0362453,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.319978,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.530201,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 7.87517,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 3291.29,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 3299.7,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.29024,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.436552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202646.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 1.28865,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.13293,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 1.93269,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 1.12,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 3.22134,
           'Execution Unit/Register Files/Runtime Dynamic': 1.25293,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.34851,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 10.4616,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 3312.38,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00224645,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00224645,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00194136,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000743168,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00120067,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00763494,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0220853,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 33.3347,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 7.28054,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.00406025,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.272904,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4061.53,
           'Instruction Fetch Unit/Runtime Dynamic': 33.6414,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 4.42795,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.53264,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.103231,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.103231,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 6.86377,
           'Load Store Unit/Runtime Dynamic': 2.14497,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.25455,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.5091,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0903405,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.090547,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.31778,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.000314339,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.94836,
           'Memory Management Unit/Runtime Dynamic': 0.0908617,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209275.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.561376,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.187379,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 30.5552,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 31.304,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 3379.56,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0067328,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.207977,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0362453,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.319978,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.545386,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 8.10071,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 3387.11,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 3395.76,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.298705,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.4464,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202646.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 1.28865,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.136737,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 1.96405,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 1.15208,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 3.2527,
           'Execution Unit/Register Files/Runtime Dynamic': 1.28881,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.353912,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 10.7641,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 3408.79,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00231506,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00231506,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00200065,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.000765862,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00123505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00786581,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0227598,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 34.2893,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 7.48904,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.00405767,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.28072,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4061.85,
           'Instruction Fetch Unit/Runtime Dynamic': 34.6047,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 4.51534,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.57458,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.106058,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.106058,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 7.01787,
           'Load Store Unit/Runtime Dynamic': 2.20368,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.261521,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.523042,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0928147,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0930246,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.32688,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.000314124,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.98839,
           'Memory Management Unit/Runtime Dynamic': 0.0933391,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209276.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.561376,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.19265,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 31.4304,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 32.1844,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 3477.87,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025},
          {'Area': 1776.72,
           'Execution Unit/Area': 1686.67,
           'Execution Unit/Complex ALUs/Area': 0.235435,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.0132646,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0067328,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.207977,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.20111,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0754163,
           'Execution Unit/Floating Point Units/Area': 4.6585,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.0656156,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0362453,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.319978,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.994829,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.373061,
           'Execution Unit/Gate Leakage': 5.03755,
           'Execution Unit/Instruction Scheduler/Area': 1561.2,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.328073,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 0.00181534,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 2.30959,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.540529,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.0225127,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.0116864,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 4.31521,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 242.241,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 1.23925,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 491.03,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 8.02857,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 18.7871,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 10.7075,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 202642.0,
           'Execution Unit/Instruction Scheduler/ROB/Area': 1318.63,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 3.07414,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 202149.0,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 3356.46,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 40.7291,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 15.306,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 3365.03,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 59.5387,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 26.0252,
           'Execution Unit/Integer ALUs/Area': 7.53393,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.424466,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.296026,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.44325,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 6.43552,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 2.41332,
           'Execution Unit/Peak Dynamic': 202646.0,
           'Execution Unit/Register Files/Area': 111.819,
           'Execution Unit/Register Files/Floating Point RF/Area': 37.7848,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 0.0316755,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 1.28865,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.135519,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.487147,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.185673,
           'Execution Unit/Register Files/Gate Leakage': 0.101689,
           'Execution Unit/Register Files/Integer RF/Area': 74.0344,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 0.0700135,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 1.95413,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 1.14182,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 1.06477,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.401522,
           'Execution Unit/Register Files/Peak Dynamic': 3.24277,
           'Execution Unit/Register Files/Runtime Dynamic': 1.27734,
           'Execution Unit/Register Files/Subthreshold Leakage': 1.55192,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.587195,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.510923,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.0650109,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.352202,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 10.6673,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.985661,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.369623,
           'Execution Unit/Runtime Dynamic': 3377.95,
           'Execution Unit/Subthreshold Leakage': 70.0229,
           'Execution Unit/Subthreshold Leakage with power gating': 29.962,
           'Gate Leakage': 5.63287,
           'Instruction Fetch Unit/Area': 47.2731,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.138516,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00229311,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 0.000757657,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.0435221,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 0.000278362,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.0168831,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00229311,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00759719,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.0039236,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.0257064,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 0.000154548,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.0142575,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00198168,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.00384344,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.00198631,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.0151917,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 8.00196e-05,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00527447,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.0007586,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00181347,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000957045,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0597838,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.0105732,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 4.63858e-05,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.0117602,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00122405,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000932505,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000494733,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.00779195,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.0199703,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.0103282,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.64954,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 0.00272758,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.177867,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.022544,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0811682,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.0435357,
           'Instruction Fetch Unit/Gate Leakage': 0.23961,
           'Instruction Fetch Unit/Instruction Buffer/Area': 11.1802,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 0.119458,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 4028.05,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 33.984,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 1.03354,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.389491,
           'Instruction Fetch Unit/Instruction Cache/Area': 4.86613,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.0421203,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 7.42235,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.00405988,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.486629,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.22691,
           'Instruction Fetch Unit/Instruction Decoder/Area': 29.7278,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.0222493,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 21.9846,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.27822,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.442943,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.166104,
           'Instruction Fetch Unit/Peak Dynamic': 4061.75,
           'Instruction Fetch Unit/Runtime Dynamic': 34.2966,
           'Instruction Fetch Unit/Subthreshold Leakage': 2.37932,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.95452,
           'Load Store Unit/Area': 9.47562,
           'Load Store Unit/Data Cache/Area': 6.84535,
           'Load Store Unit/Data Cache/Gate Leakage': 0.0279261,
           'Load Store Unit/Data Cache/Peak Dynamic': 4.48738,
           'Load Store Unit/Data Cache/Runtime Dynamic': 1.56117,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.527675,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.25085,
           'Load Store Unit/Gate Leakage': 0.0841218,
           'Load Store Unit/LoadQ/Area': 0.0836782,
           'Load Store Unit/LoadQ/Gate Leakage': 0.00059896,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.105154,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.105154,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00941961,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00536918,
           'Load Store Unit/Peak Dynamic': 6.96857,
           'Load Store Unit/Runtime Dynamic': 2.1849,
           'Load Store Unit/StoreQ/Area': 0.322079,
           'Load Store Unit/StoreQ/Gate Leakage': 0.00329971,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.259291,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.518582,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0345621,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0197004,
           'Load Store Unit/Subthreshold Leakage': 0.886727,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.394071,
           'Memory Management Unit/Area': 1.10051,
           'Memory Management Unit/Dtlb/Area': 0.0879726,
           'Memory Management Unit/Dtlb/Gate Leakage': 0.00088729,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0920231,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0922329,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.0155699,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00887485,
           'Memory Management Unit/Gate Leakage': 0.057119,
           'Memory Management Unit/Itlb/Area': 0.301552,
           'Memory Management Unit/Itlb/Gate Leakage': 0.00393464,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.32397,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.000314311,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.0413758,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0235842,
           'Memory Management Unit/Peak Dynamic': 3.97558,
           'Memory Management Unit/Runtime Dynamic': 0.0925476,
           'Memory Management Unit/Subthreshold Leakage': 0.372016,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.150611,
           'Peak Dynamic': 209276.0,
           'Renaming Unit/Area': 27.8071,
           'Renaming Unit/FP Front End RAT/Area': 0.168486,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.00489731,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 78.3725,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.561376,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0437281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.024925,
           'Renaming Unit/Free List/Area': 7.5975,
           'Renaming Unit/Free List/Gate Leakage': 0.00102434,
           'Renaming Unit/Free List/Peak Dynamic': 7.41375,
           'Renaming Unit/Free List/Runtime Dynamic': 0.190964,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.0190978,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 0.00884518,
           'Renaming Unit/Gate Leakage': 0.0906085,
           'Renaming Unit/Int Front End RAT/Area': 19.3301,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 0.0323898,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 2465.83,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 31.1505,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.500294,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.285168,
           'Renaming Unit/Peak Dynamic': 2556.62,
           'Renaming Unit/Runtime Dynamic': 31.9028,
           'Renaming Unit/Subthreshold Leakage': 0.87819,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.437089,
           'Runtime Dynamic': 3446.42,
           'Subthreshold Leakage': 76.417,
           'Subthreshold Leakage with power gating': 32.6025}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 0.000525754405882343,
          'Runtime Dynamic': 0.000525754405882343,
          'Subthreshold Leakage': 4.252,
          'Subthreshold Leakage with power gating': 4.252},
 'L2': [{'Area': 22.2273,
         'Gate Leakage': 0.0518439,
         'Peak Dynamic': 0.0900616,
         'Runtime Dynamic': 0.0496876,
         'Subthreshold Leakage': 2.01996,
         'Subthreshold Leakage with power gating': 0.908099}],
 'L3': [{'Area': 61.9075,
         'Gate Leakage': 0.0484137,
         'Peak Dynamic': 3.26732e-05,
         'Runtime Dynamic': 1.1957e-05,
         'Subthreshold Leakage': 6.80085,
         'Subthreshold Leakage with power gating': 3.32364}],
 'Processor': {'Area': 7207.04,
               'Gate Leakage': 22.6747,
               'Peak Dynamic': 837095.0,
               'Peak Power': 837433.0,
               'Runtime Dynamic': 12426.3,
               'Subthreshold Leakage': 314.937,
               'Subthreshold Leakage with power gating': 135.294,
               'Total Cores/Area': 7106.89,
               'Total Cores/Gate Leakage': 22.5315,
               'Total Cores/Peak Dynamic': 837095.0,
               'Total Cores/Runtime Dynamic': 12426.2,
               'Total Cores/Subthreshold Leakage': 305.668,
               'Total Cores/Subthreshold Leakage with power gating': 130.41,
               'Total L2s/Area': 22.2273,
               'Total L2s/Gate Leakage': 0.0518439,
               'Total L2s/Peak Dynamic': 0.0900616,
               'Total L2s/Runtime Dynamic': 0.0496876,
               'Total L2s/Subthreshold Leakage': 2.01996,
               'Total L2s/Subthreshold Leakage with power gating': 0.908099,
               'Total L3s/Area': 61.9075,
               'Total L3s/Gate Leakage': 0.0484137,
               'Total L3s/Peak Dynamic': 3.26732e-05,
               'Total L3s/Runtime Dynamic': 1.1957e-05,
               'Total L3s/Subthreshold Leakage': 6.80085,
               'Total L3s/Subthreshold Leakage with power gating': 3.32364,
               'Total Leakage': 337.611,
               'Total NoCs/Area': 16.0146,
               'Total NoCs/Gate Leakage': 0.0429624,
               'Total NoCs/Peak Dynamic': 0.0,
               'Total NoCs/Runtime Dynamic': 0.0,
               'Total NoCs/Subthreshold Leakage': 0.448008,
               'Total NoCs/Subthreshold Leakage with power gating': 0.168003}}